# Generated by Django 4.2.6 on 2023-11-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
